apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xmtpd.fullname" . }}-contracts-config
data:
  contracts.json: |
    {
      "appChainDeploymentBlock": 69147,
      "appChainFactory": "0x95D0A57041259b959DfC53530F902d0c2B8DDF5E",
      "appChainGateway": "0xE3A28819f015F739Bd8367A81f0f6ebC9D6553b4",
      "appChainId": 241320161,
      "appChainNativeToken": "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
      "appChainParameterRegistry": "0xDe2bF8Bbdb50aB5D1645C89145b08Ef787E4D81a",
      "deployer": "0xBC0d5ADdb45E3F5b37806cacf9112C16a54414a8",
      "distributionManager": "0xCf51C25aBe847B97eD4F5e62419AC2aACE92345B",
      "groupMessageBroadcaster": "0xBE03f49ea7010f2c90D57aa7656E30E81a79D3B6",
      "identityUpdateBroadcaster": "0x46bce0d43aC4433e7FC0F5f37d694a41e75A5c46",
      "nodeRegistry": "0x5275FfA7D1f5aBd4159Ae38925fD9F4D5686725E",
      "payerRegistry": "0x2B019EAfE0910a16394D78f3E930bB4c946B5E9e",
      "payerReportManager": "0x4f2aD70408A47ab2641d798da4F672D25eB30c4F",
      "rateRegistry": "0x070eFE6e07b2cb17c6c7a3AB276ce79745e4A65A",
      "settlementChainDeploymentBlock": 26900619,
      "settlementChainFactory": "0x95D0A57041259b959DfC53530F902d0c2B8DDF5E",
      "settlementChainGateway": "0xE3A28819f015F739Bd8367A81f0f6ebC9D6553b4",
      "settlementChainId": 84532,
      "settlementChainParameterRegistry": "0xDe2bF8Bbdb50aB5D1645C89145b08Ef787E4D81a"
    }